### ISSUE TITLE
Feature request: make a version without "Access your data for all websites"

### ISSUE THREAD

**Issue by eggsgent** [bros0215/eyes-alarm#1]
Hi, I'd like to see a version of this extension without the "Access your data for all websites" permission.

Since the user supposedly is watching the screen for an extended amount of time, I think that a visual cue in is enough, a sound alarm would fit more if I'd sleep in front of the screen.

For a stronger visual cue, an alternative could for example be to load a new tab with as nice full window notification content instead of using OS level notifications.

**Comment by artyomliou** [comment]
Hello, sorry for late reply. 
I just published a new version without "Access your data for all websites" as manifest V3 required.
And thank you for functional advice.
